openapi: 3.0.3
info:
  title: Customers - OpenAPI 3.0
  description: |-
    Customers API Spec
  version: 1.0.0
servers:
  - url: api/v1
paths:
  /customers:
    post:
      tags:
        - customer
      summary: Add a new customer
      description: Add a new customer
      operationId: addCustomer
      requestBody:
        description: Create a new customer
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Bad request
    get:
      tags:
        - customers
      summary: Get all customers
      description: Get all customers
      operationId: getCustomers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        name:
          type: string
          example: John
        surname:
          type: string
          example: Stamos
        photo:
          type: string
          example: image_path/image_name.png