spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/auth/realms/SpringBootKeycloak
          jwk-set-uri: http://localhost:28080/auth/realms/SpringBootKeycloak/protocol/openid-connect/certs